version: "3"

services:
  dump1090-json:
    image: iqtlabs/edgetech-dump1090-json:latest
    build:
      context: ./dump1090-json
      dockerfile: ./Dockerfile
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
    env_file:
      - ./dump1090-json.env
