name: Docker Build Testing

on:
  push:
    branches: [ "main" ]

jobs:
  push_to_registry:
    name: Test Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        env: 
          DOCKER_FOLDER: "dump1090-json"
        with:
          context: ${{ env.DOCKER_FOLDER }}
          platforms: linux/arm64,linux/amd64
          push: false
          tags: ${{ vars.DOCKER_NAMESPACE }}/${{ github.event.repository.name }}:${{ github.event.release.name }}
